export default function VegetativeStage() {
  return (
    <>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
      <div>Table1</div>
    </>
  );
}
